/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mario_maker_guatemalteco;

/**
 *
 * @author asus
 */
public class CargadeObjetos extends javax.swing.JFrame {

    static Listadoble listitadepersonajes = new Listadoble();
    
    /**
     * Creates new form CargadeObjetos
     */
    public CargadeObjetos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btsuelo = new javax.swing.JButton();
        btnpared = new javax.swing.JButton();
        txtsuelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtpared = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btngoomba = new javax.swing.JButton();
        txtgoomba = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnkoopa = new javax.swing.JButton();
        txtkoopa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnficha = new javax.swing.JButton();
        btnhongo = new javax.swing.JButton();
        btnmario = new javax.swing.JButton();
        btncastillo = new javax.swing.JButton();
        txtficha = new javax.swing.JTextField();
        txthongo = new javax.swing.JTextField();
        txtmario = new javax.swing.JTextField();
        txtcastillo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeJuego/Suelo.png"))); // NOI18N
        jLabel1.setText("SUELO");

        btsuelo.setText("AGREGAR");
        btsuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsueloActionPerformed(evt);
            }
        });

        btnpared.setText("AGREGAR");
        btnpared.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnparedActionPerformed(evt);
            }
        });

        txtsuelo.setText("suelito");
        txtsuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsueloActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeJuego/Pared.png"))); // NOI18N
        jLabel2.setText("PARED");

        txtpared.setText("paredita");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeJuego/Gomba.png"))); // NOI18N
        jLabel3.setText("GOOMBA");

        btngoomba.setText("AGREGAR");
        btngoomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngoombaActionPerformed(evt);
            }
        });

        txtgoomba.setText("goombita");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeJuego/Kopa.png"))); // NOI18N
        jLabel4.setText("KOOPA (TORTUGA)");

        btnkoopa.setText("AGREGAR");
        btnkoopa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkoopaActionPerformed(evt);
            }
        });

        txtkoopa.setText("tortuguita");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeJuego/ficha.png"))); // NOI18N
        jLabel5.setText("FICHA");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeJuego/hongo.png"))); // NOI18N
        jLabel6.setText("HONGO DE VIDA");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeJuego/mario.png"))); // NOI18N
        jLabel7.setText("MARIO");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesdeJuego/castillo.png"))); // NOI18N
        jLabel8.setText("CASTILLO");

        btnficha.setText("AGREGAR");
        btnficha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfichaActionPerformed(evt);
            }
        });

        btnhongo.setText("AGREGAR");
        btnhongo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhongoActionPerformed(evt);
            }
        });

        btnmario.setText("AGREGAR");
        btnmario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmarioActionPerformed(evt);
            }
        });

        btncastillo.setText("AGREGAR");
        btncastillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncastilloActionPerformed(evt);
            }
        });

        txtficha.setText("fichita");

        txthongo.setText("honguito");

        txtmario.setText("marito");

        txtcastillo.setText("castillito");

        jButton1.setText("pila");

        jButton2.setText("cola");

        jButton3.setText("MOSTRAR OBJETOS LISTA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btsuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnpared, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btngoomba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnkoopa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnficha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnhongo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnmario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncastillo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtsuelo)
                    .addComponent(txtpared)
                    .addComponent(txtgoomba)
                    .addComponent(txtkoopa)
                    .addComponent(txtficha)
                    .addComponent(txthongo)
                    .addComponent(txtmario)
                    .addComponent(txtcastillo))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButton3)))
                .addGap(274, 274, 274))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnpared)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtpared, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(btngoomba))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtgoomba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(btnkoopa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtkoopa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(btnficha))
                        .addGap(3, 3, 3)
                        .addComponent(txtficha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(btnhongo))
                        .addGap(1, 1, 1)
                        .addComponent(txthongo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(btnmario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtmario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(btncastillo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcastillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btsuelo)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(106, 106, 106)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btsueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsueloActionPerformed
        // TODO add your handling code here:
        listitadepersonajes.agregarpersonajesalinicio(new Personaje (txtsuelo.getText(),"suelitoo"));
        
    }//GEN-LAST:event_btsueloActionPerformed

    private void btnparedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnparedActionPerformed
        // TODO add your handling code here:
         listitadepersonajes.agregarpersonajesalinicio(new Personaje (txtpared.getText(),"pareditaa"));
    }//GEN-LAST:event_btnparedActionPerformed

    private void btngoombaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngoombaActionPerformed
        // TODO add your handling code here:
         listitadepersonajes.agregarpersonajesalinicio(new Personaje (txtgoomba.getText(),"goombitaa"));
    }//GEN-LAST:event_btngoombaActionPerformed

    private void btnkoopaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkoopaActionPerformed
        // TODO add your handling code here:
         listitadepersonajes.agregarpersonajesalinicio(new Personaje (txtkoopa.getText(),"tortuguita"));
    }//GEN-LAST:event_btnkoopaActionPerformed

    private void btnfichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfichaActionPerformed
        // TODO add your handling code here:
         listitadepersonajes.agregarpersonajesalinicio(new Personaje (txtficha.getText(),"fichitaa"));
    }//GEN-LAST:event_btnfichaActionPerformed

    private void btnhongoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhongoActionPerformed
        // TODO add your handling code here:
         listitadepersonajes.agregarpersonajesalinicio(new Personaje (txthongo.getText(),"honguito"));
    }//GEN-LAST:event_btnhongoActionPerformed

    private void btnmarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmarioActionPerformed
        // TODO add your handling code here:
         listitadepersonajes.agregarpersonajesalinicio(new Personaje (txtmario.getText(),"MARITOO"));
    }//GEN-LAST:event_btnmarioActionPerformed

    private void btncastilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncastilloActionPerformed
        // TODO add your handling code here:
         listitadepersonajes.agregarpersonajesalinicio(new Personaje (txtcastillo.getText(),"CASTILLOOO"));
    }//GEN-LAST:event_btncastilloActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      //  listitadepersonajes.mostrarListainiciofin();
        PantalladeMostrar mostrarpersonajes = new PantalladeMostrar();
        mostrarpersonajes.setVisible(true);
        mostrarpersonajes.show();
                this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtsueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsueloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargadeObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargadeObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargadeObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargadeObjetos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CargadeObjetos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncastillo;
    private javax.swing.JButton btnficha;
    private javax.swing.JButton btngoomba;
    private javax.swing.JButton btnhongo;
    private javax.swing.JButton btnkoopa;
    private javax.swing.JButton btnmario;
    private javax.swing.JButton btnpared;
    private javax.swing.JButton btsuelo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtcastillo;
    private javax.swing.JTextField txtficha;
    private javax.swing.JTextField txtgoomba;
    private javax.swing.JTextField txthongo;
    private javax.swing.JTextField txtkoopa;
    private javax.swing.JTextField txtmario;
    private javax.swing.JTextField txtpared;
    private javax.swing.JTextField txtsuelo;
    // End of variables declaration//GEN-END:variables
}
